Sort settings

diff --git a/bin/common/.local/bin/update-kb-settings b/bin/common/.local/bin/update-kb-settings
--- a/bin/common/.local/bin/update-kb-settings
+++ b/bin/common/.local/bin/update-kb-settings
@@ -2,33 +2,7 @@
 
 set -eu -o pipefail
 
-if [[ $(uname) == Darwin ]]; then
-  # Remap Caps Lock as Control (see https://developer.apple.com/library/archive/technotes/tn2450/_index.html)
-  modifiermapping="$(
-    hidutil list --ndjson | jq -r '
-      select(
-        ."Built-In" == true and
-        .PrimaryUsagePage == 1 and
-        .PrimaryUsage == 6
-      )
-      | "com.apple.keyboard.modifiermapping.\(.VendorID)-\(.ProductID)-0"
-    ' | head -n1
-  )"
-  if [[ -n $modifiermapping ]]; then
-    hidutil property --set '{
-      "UserKeyMapping": [{
-        "HIDKeyboardModifierMappingSrc": 0x700000039,
-        "HIDKeyboardModifierMappingDst": 0x7000000E0,
-      }]
-    }'
-    defaults -currentHost write NSGlobalDomain "$modifiermapping" -array '{
-      HIDKeyboardModifierMappingSrc = 30064771129;
-      HIDKeyboardModifierMappingDst = 30064771296;
-    }'
-  else
-    echo "Unable to find a built-in keyboard for persistent modifier mapping." >&2
-  fi
-elif [[ $(uname) == Linux ]]; then
+if [[ $(uname) == Linux ]]; then
   xset r rate 180 50
   xsetroot -cursor_name left_ptr
 
@@ -71,6 +45,32 @@ elif [[ $(uname) == Linux ]]; then
 
     # Disable middle click on trackpad (or rather make it the same as left click)
     xinput set-button-map "$TOUCHPAD" 1 1 3 4 5 6 7
+  fi
+elif [[ $(uname) == Darwin ]]; then
+  # Remap Caps Lock as Control (see https://developer.apple.com/library/archive/technotes/tn2450/_index.html)
+  modifiermapping="$(
+    hidutil list --ndjson | jq -r '
+      select(
+        ."Built-In" == true and
+        .PrimaryUsagePage == 1 and
+        .PrimaryUsage == 6
+      )
+      | "com.apple.keyboard.modifiermapping.\(.VendorID)-\(.ProductID)-0"
+    ' | head -n1
+  )"
+  if [[ -n $modifiermapping ]]; then
+    hidutil property --set '{
+      "UserKeyMapping": [{
+        "HIDKeyboardModifierMappingSrc": 0x700000039,
+        "HIDKeyboardModifierMappingDst": 0x7000000E0,
+      }]
+    }'
+    defaults -currentHost write NSGlobalDomain "$modifiermapping" -array '{
+      HIDKeyboardModifierMappingSrc = 30064771129;
+      HIDKeyboardModifierMappingDst = 30064771296;
+    }'
+  else
+    echo "Unable to find a built-in keyboard for persistent modifier mapping." >&2
   fi
 else
   echo "Unsupported platform: $(uname)" >&2
