Start adding support for running this via systemd

diff --git a/bin/linux/.local/bin/duplicity-backup b/bin/linux/.local/bin/duplicity-backup
--- a/bin/linux/.local/bin/duplicity-backup
+++ b/bin/linux/.local/bin/duplicity-backup
@@ -8,22 +8,30 @@ if [[ $EUID -ne 0 ]]; then
    exit 1
 fi
 
-if [ ! -f "$CREDS" ]
+# If the env vars aren't set (likely because the script was run directly rather
+# than from systemd), let's read them from the config file and export them.
+if [ -z "$PASSPHRASE" ]
 then
-   echo "Credentials cannot be read at $CREDS"
-   exit 1
+   if [ ! -f "$CREDS" ]
+   then
+      echo "Credentials cannot be read at $CREDS"
+      exit 1
+   fi
+
+   while read -r line
+   do
+      if [[ "$line" == \#* ]] || [[ "$line" != *=* ]]
+      then
+         continue
+      fi
+      export $line
+   done <"$CREDS"
 fi
 
-while read -r line
-do
-   if [[ "$line" == \#* ]] || [[ "$line" != *=* ]]
-   then
-      continue
-   fi
-   export $line
-done <"$CREDS"
-
-duplicity --exclude /home/damien/.cache --exclude /home/damien/data /home "$DEST"
+duplicity --exclude /home/damien/.cache \
+          --exclude /home/damien/data \
+          /home \
+          "$DEST"
 
 duplicity remove-all-but-n-full 64 --force "$DEST"
 duplicity cleanup --force "$DEST"
